version: "3"
services:
    rclone:
        image: pfidr/rclone:latest
        container_name: rclone
        environment:
          PUID: "${PUID}"
          PGID: "${PGID}"
          SYNC_SRC: "/source"
          SYNC_DEST: "crypt:/current"
          SYNC_OPTS_EVAL: "--backup-dir crypt:/archive/`date -I`"
          CRON: "${RCLONE_CRON}"
          CRON_ABORT: "${RCLONE_CRON_ABORT}"
          OUTPUT_LOG: 1
          ROTATE_LOG: 60
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - "${APPDATA}/backup/work:/source" 
          - "${APPDATA}/backup:/config"
          - "${APPDATA}/backup/logs:/logs"
        restart: always
networks:
  default:
    external:
      name: backup
