version: "3"
services:
     wordpress:
        image: wordpress:latest
        container_name: wordpress
        environment:
          PUID: "${PUID}"
          PGID: "${PGID}"
          WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
          WORDPRESS_DB_HOST: mariadb:3306
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - "${APPDATA_WEB}/wordpress:/var/www/html"
       labels:
         traefik.enable: "true"
         traefik.http.routers.wordpress.rule: "Host(`${DOMAIN}`)"
         traefik.http.routers.wordpress.entrypoints: "web"
         traefik.http.routers.wordpress.middlewares: "redirect@file"
         traefik.http.routers.wordpress-secured.rule: "Host(`${DOMAIN}`)"
         traefik.http.routers.wordpress-secured.entrypoints: "websecure"
         traefik.http.routers.wordpress-secured.tls: "true"
         traefik.http.routers.wordpress-secured.tls.options: "securetls@file"
         traefik.http.routers.wordpress-secured.tls.certresolver: "le"
         traefik.http.routers.wordpress-secured.middlewares: "secureHeaders@file,googleAuth@file"
         traefik.http.services.wordpress-secured.loadbalancer.server.port: "80"
       restart: always
networks:
  default:
    external:
      name: web
