version: "3"
services:
    hiemdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        environment:
          PUID: "${PUID}"
          PGID: "${PGID}"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - "${APPDATA_WEB}/heimdall:/config"
        labels:
          traefik.enable: "true"
          traefik.http.routers.heimdall.rule: "Host(`admin.${DOMAIN}`)"
          traefik.http.routers.heimdall.entrypoints: "web"
          traefik.http.routers.heimdall.middlewares: "redirect@file"
          traefik.http.routers.heimdall-secured.rule: "Host(`admin.${DOMAIN}`)"
          traefik.http.routers.heimdall-secured.entrypoints: "websecure"
          traefik.http.routers.heimdall-secured.tls: "true"
          traefik.http.routers.heimdall-secured.tls.options: "securetls@file"
          traefik.http.routers.heimdall-secured.tls.certresolver: "le"
          traefik.http.routers.heimdall-secured.middlewares: "secureHeaders@file,googleAuth@file"
          traefik.http.services.heimdall-secured.loadbalancer.server.port: "80"
        restart: always
networks:
  default:
    external:
      name: web
